// User-related enums
export enum ROLE {
	STUDENT = "STUDENT",
	INSTRUCTOR = "INSTRUCTOR",
	ADMIN = "ADMIN",
}

export enum ROLE_STATUS {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	SUSPENDED = "SUSPENDED",
}

export enum VERIFICATION_STATUS {
	PENDING = "PENDING",
	VERIFIED = "VERIFIED",
	REJECTED = "REJECTED",
}

export enum LEARNING_STYLES {
	VISUAL = "VISUAL",
	AUDITORY = "AUDITORY",
	KINESTHETIC = "KINESTHETIC",
	READING_WRITING = "READING_WRITING",
}

export enum PACE_PREFERENCE {
	SLOW = "SLOW",
	MODERATE = "MODERATE",
	FAST = "FAST",
}

export enum REVIEW_DISCRIMINANT {
	COURSE = "COURSE",
	INSTRUCTOR = "INSTRUCTOR",
}

// Course-related enums
export enum COURSE_LEVEL {
	BEGINNER = "BEGINNER",
	INTERMEDIATE = "INTERMEDIATE",
	ADVANCED = "ADVANCED",
	EXPERT = "EXPERT",
}

export enum COURSE_STATUS {
	DRAFT = "DRAFT",
	PUBLISHED = "PUBLISHED",
	ARCHIVED = "ARCHIVED",
	UNDER_REVIEW = "UNDER_REVIEW",
}

export enum LESSON_TYPE {
	VIDEO = "VIDEO",
	TEXT = "TEXT",
	INTERACTIVE = "INTERACTIVE",
	MIXED = "MIXED",
}

export enum DIFFICULTY_LEVEL {
	EASY = "EASY",
	MEDIUM = "MEDIUM",
	HARD = "HARD",
	VERY_HARD = "VERY_HARD",
}

export enum LEARNING_TECHNIQUE {
	LECTURE = "LECTURE",
	PRACTICE = "PRACTICE",
	DISCUSSION = "DISCUSSION",
	PROJECT = "PROJECT",
	QUIZ = "QUIZ",
}

export enum LESSON_CONTENT_TYPE {
	VIDEO = "VIDEO",
	TEXT = "TEXT",
	AUDIO = "AUDIO",
	INTERACTIVE = "INTERACTIVE",
	DOCUMENT = "DOCUMENT",
}

export enum ASSIGNMENT_TYPE {
	FILE_UPLOAD = "FILE_UPLOAD",
	TEXT = "TEXT",
	URL = "URL",
	MULTIPLE = "MULTIPLE",
}

export enum SUBMISSION_STATUS {
	PENDING = "PENDING",
	SUBMITTED = "SUBMITTED",
	GRADED = "GRADED",
	REJECTED = "REJECTED",
}

export enum DISCRIMINANT_RESOURCE {
	COURSE = "COURSE",
	LESSON = "LESSON",
	SECTION = "SECTION",
	ASSIGNMENT = "ASSIGNMENT",
	COURSE_INFO = "COURSE_INFO",
}

export enum RESOURCE_TYPE {
	VIDEO = "VIDEO",
	DOCUMENT = "DOCUMENT",
	IMAGE = "IMAGE",
	AUDIO = "AUDIO",
	LINK = "LINK",
	TEXT = "TEXT",
}
